version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

#  kibana:
#    image: kibana:7.5.1
#    ports:
#      - 5601:5601
#    depends_on:
#      - elasticsearch

  queue:
    build: ./docker
    image: server
    container_name: queue
    volumes:
      - ./:/usr/local/django_nas
    command: >
      sh -c "python manage.py rqworker"
    depends_on:
      - redis

  django:
    build: ./docker
    image: server
    volumes:
      - ./:/usr/local/django_nas
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:80"
    ports:
      - 80:80
    depends_on:
      - queue
#      - elasticsearch

  redis:
    image: redis:latest
    deploy:
      replicas: 1
    volumes:
      - ./data:/data

  reindex:
    build: ./docker
    image: server
    volumes:
      - ./:/usr/local/django_nas
    command: >
      sh -c "python manage.py search_index --rebuild"
    depends_on:
      - django



#  samba:
#   container_name: samba
#   hostname: samba
#   image: sixeyed/samba
#   volumes:
#      - ./django-nas/samba:/mnt/sharing
#   ports:
#     - 139:139
#     - 445:445
#     - 137:137
#     - 138:138
##      - "445:445"
##      - "137:137/udp"
##      - "138:138/udp"
#   command: samba.sh -s "file;/mnt/sharing/file;yes;no;yes;all"
#   restart: always
