version: "3"
services:
  queue:
    build: ./docker
    image: server
    container_name: queue
    volumes:
      - ./:/usr/local/django_nas
    command: >
      sh -c "python manage.py rqworker"
    depends_on:
      - redis
  django-test:
    build: ./docker
    image: server
    volumes:
      - ./:/usr/local/django_nas
      - ./test-files:/test-files
    command: "python manage.py test"
    depends_on:
      - queue

  django:
    build: ./docker
    image: server
    volumes:
      - ./:/usr/local/django_nas
      - ./test-files:/test-files
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:80"
    ports:
      - 80:80
    depends_on:
      - queue

  django-makemigrations:
    build: ./docker
    image: server
    volumes:
      - ./:/usr/local/django_nas
    command: "python manage.py makemigrations"

    depends_on:
      - queue

  django-migrate:
    build: ./docker
    image: server
    volumes:
      - ./:/usr/local/django_nas
    command: "python manage.py migrate"

    depends_on:
      - queue

  redis:
    image: redis:latest
    deploy:
      replicas: 1
    volumes:
      - ./data:/data
