version: "3"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: django-nas
      POSTGRES_USER: django-nas
  queue:
    build: ./docker
    image: server
    container_name: queue
    volumes:
      - ./:/usr/local/django_nas
    command: >
      sh -c "python manage.py rqworker"
    depends_on:
      - redis
  django-test:
    build: ./docker
    image: server
    volumes:
      - ./:/usr/local/django_nas
      - ./test-files:/test-files
    command: "python manage.py test"
    depends_on:
      - queue
      - db

  django:
    build: ./docker
    image: server
    container_name: django
    volumes:
      - ./:/usr/local/django_nas
      - ./test-files:/test-files
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:80"
    ports:
      - 80:80
    depends_on:
      - queue
      - db

  django-makemigrations:
    build: ./docker
    image: server
    volumes:
      - ./:/usr/local/django_nas
    command: "python manage.py makemigrations"

    depends_on:
      - queue
      - db

  django-migrate:
    build: ./docker
    image: server
    volumes:
      - ./:/usr/local/django_nas
    command: "python manage.py migrate"

    depends_on:
      - queue
      - db

  redis:
    image: redis:latest
    deploy:
      replicas: 1
    volumes:
      - ./data:/data
