# Generated by Django 3.0.3 on 2020-04-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmetadata',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
