# Generated by Django 3.0.3 on 2020-04-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0002_musicmetadata_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmetadata',
            name='lyrics',
            field=models.TextField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='musicmetadata',
            name='picture',
            field=models.FileField(blank=True, max_length=10000, null=True, upload_to='music-cover/%Y/%m/%d'),
        ),
    ]
