# Generated by Django 2.2.7 on 2019-12-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0002_auto_20191201_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
