# Generated by Django 2.2.7 on 2019-12-01 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0003_remove_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='object_type',
            field=models.CharField(choices=[('Image', 'image'), ('Text', 'txt'), ('File', 'file')], default='file', max_length=128),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='nas.Folder'),
        ),
    ]
