# Generated by Django 3.0.7 on 2020-06-28 13:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0004_auto_20200628_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemetadata',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
