# Generated by Django 3.0.7 on 2021-01-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0004_auto_20200628_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmetadata',
            name='track',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='musicmetadata',
            name='year',
            field=models.CharField(blank=True, default='2020', max_length=128, null=True),
        ),
    ]
