# Generated by Django 2.2.7 on 2019-12-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0006_auto_20191202_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('parent', 'name')},
        ),
    ]
