# Generated by Django 3.0 on 2019-12-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0009_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='transcode_filepath',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
