# Generated by Django 3.0 on 2019-12-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0010_file_transcode_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='transcode_filepath',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
