# Generated by Django 3.0 on 2019-12-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0011_auto_20191214_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='transcode_filepath',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
