# Generated by Django 3.0 on 2019-12-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0013_file_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='size',
            field=models.FloatField(default=0),
        ),
    ]
