# Generated by Django 3.0 on 2019-12-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0014_auto_20191216_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='size',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
