# Generated by Django 3.0 on 2020-04-13 02:15

from django.db import migrations, models
import nas.models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0016_file_has_uploaded_to_cloud'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('album', models.CharField(blank=True, max_length=1024, null=True)),
                ('artist', models.TextField(blank=True, max_length=1024, null=True)),
                ('year', models.IntegerField(default=2020)),
                ('track', models.IntegerField(default=0)),
                ('genre', models.IntegerField(default=0)),
                ('picture', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=1000000, upload_to=nas.models.user_directory_path),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set(),
        ),
    ]
