# Generated by Django 3.0 on 2020-04-13 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0017_auto_20200413_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmetadata',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musicmetadata',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nas.File'),
        ),
    ]
