# Generated by Django 3.0 on 2020-04-13 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0018_auto_20200413_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmetadata',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='nas.File'),
        ),
    ]
