# Generated by Django 3.0 on 2020-04-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0019_auto_20200413_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmetadata',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='music-cover/%Y/%m/%d'),
        ),
    ]
