# Generated by Django 3.0 on 2020-04-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0021_auto_20200413_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmetadata',
            name='duration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
