# Generated by Django 3.0 on 2020-04-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0022_auto_20200413_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmetadata',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
