# Generated by Django 3.0 on 2020-04-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0024_auto_20200413_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmetadata',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
