# Generated by Django 3.0 on 2020-04-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0025_musicmetadata_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmetadata',
            name='album_artist',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
