# Generated by Django 3.0 on 2020-04-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0026_musicmetadata_album_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('sender', models.CharField(default='system', max_length=128)),
                ('log_type', models.CharField(choices=[('CREATED', 'created'), ('DELETED', 'deleted'), ('UPDATED', 'updated'), ('LOG', 'log')], max_length=128)),
            ],
        ),
    ]
