# Generated by Django 3.0 on 2020-04-16 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0028_auto_20200416_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='show_in_folder',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='nas.BookCollection'),
        ),
    ]
