name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker
      run: docker-compose build .
    - name: Start Docker
      run: |
        docker-compose up -d django
    - name: Run Tests
      run: |
        docker-compose run django-test
