name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: start Docker deamon
      run:  docker-machine start default
    - name: Start Docker
      run: |
        docker-compose up -d django
    - name: Run Tests
      run: |
        docker-compose run django-test
